### ISSUE TITLE
HTTP USER_AGENT Not Found

### ISSUE THREAD

**Issue by Michany** [timothyqiu/xiami-downloader#21]
When I try to login in with username and password,
``` 
Traceback (most recent call last):
  File "c:\users\70242\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\70242\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\70242\AppData\Local\Programs\Python\Python36\Scripts\xiami.exe\__main__.py", line 9, in <module>
  File "c:\users\70242\appdata\local\programs\python\python36\lib\site-packages\xiami_downloader\cli.py", line 432, in main
    cookie = core.login(args.username, args.password)
  File "c:\users\70242\appdata\local\programs\python\python36\lib\site-packages\xiami_downloader\core.py", line 48, in login
    'User-Agent': http.USER_AGENT,
AttributeError: module 'xiami_downloader.http' has no attribute 'USER_AGENT'
```

Turns out ``USER_AGENT`` is defined right in ``core.py``, so you should remove ``http.``

**Comment by timothyqiu** [comment]
Thank you 🎉
